# Алгоритмы Витерби

In [1]:
import numpy as np

In [2]:
def state_to_index(state):
    mapping = {'О': 0, 'Р': 1}
    return mapping[state]

In [23]:
def viterbi(open_states, P, A, B):
    assert len(P) == A.shape[0] == B.shape[0]
    psi = []
    idx = state_to_index(open_states[0])
    epsilon = P * B[:, idx]
    for i, open_state in enumerate(open_states[1:]):
        idx = state_to_index(open_state)
        psi.append(np.argmax(A * epsilon, axis=0))
        epsilon = np.max(A * epsilon, axis=0) * B[:, idx]
    hidden_states = []
    hidden_states.append(np.argmax(epsilon))
    n = len(psi)
    for i in range(1, n):
        hidden_states.append(psi[n - i][hidden_states[i - 1]])
    return hidden_states

In [3]:
def viterbi_algorithm(A, states, emissions, prior_probabilities, B, sequence):
    probabilities = []
    
    emissions_dict = dict(zip(emissions, list(range(len(emissions)))))    
    emissions_sequence = []
    for item in sequence:
        emissions_sequence.append(emissions_dict[item])

    probabilities.append(
        tuple(
            prior_probabilities[state]*B[state, emissions_sequence[0]]
            for state in range(len(states)))
    )

    for i in range(1, len(emissions_sequence)):
        previous_probabilities = probabilities[-1]
        current_probabilities = []
        for col in range(len(A[0,:])):
            p = max(
                previous_probabilities[state]*A[state,col]*B[col,emissions_sequence[i]]
                for state in range(len(states))
            )
            current_probabilities.append(p)
        probabilities.append(tuple(current_probabilities))

    hidden_states_sequence = []
    for i in probabilities:
        hidden_state = states[np.argmax(i)]
        hidden_states_sequence.append(hidden_state)
    
    return hidden_states_sequence

## Тестирование

In [12]:
open_states = 'ОРОРОРООРРРРРРРРРРОООООООО'

In [13]:
P = np.array([0.5, 0.5])
P

array([0.5, 0.5])

## Тест 1

In [14]:
B = np.array(
    [
        [0.5, 0.5],
        [0.1, 0.9]
    ],
)
B

array([[0.5, 0.5],
       [0.1, 0.9]])

In [15]:
A = np.array(
    [
        [0.8, 0.2],
        [0.2, 0.8]
    ],
)
A

array([[0.8, 0.2],
       [0.2, 0.8]])

In [16]:
viterbi_algorithm(A, [1, 2], ['О', 'Р'], P, B, open_states)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1]

In [24]:
viterbi(open_states, P, A, B)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

## Тест 2

In [31]:
B = np.array(
    [
        [0.5,  0.5],
        [0.51, 0.49]
    ],
)
B

array([[0.5 , 0.5 ],
       [0.51, 0.49]])

In [33]:
A = np.array(
    [
        [0.5, 0.5],
        [0.5, 0.5]
    ],
)
A

array([[0.5, 0.5],
       [0.5, 0.5]])

In [28]:
viterbi_algorithm(A, [1, 2], ['О', 'Р'], P, B, open_states)

[2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2]

In [29]:
viterbi(open_states, P, A, B)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]