# Алгоритмы Витерби

In [1]:
import numpy as np

In [12]:
def open_state_to_index(state):
    mapping = {'О': 0, 'Р': 1}
    return mapping[state]

def index_to_hidden_state(idx):
    mapping = [1, 2]
    return mapping[idx]

In [14]:
def viterbi(open_states, P, A, B):
    assert len(P) == A.shape[0] == B.shape[0]
    psi = []
    idx = state_to_index(open_states[0])
    epsilon = (P * B[:, idx]).reshape(-1, 1)
    for i, open_state in enumerate(open_states[1:]):
        idx = state_to_index(open_state)
        psi.append(np.argmax(A * epsilon, axis=0))
        epsilon = (np.max(A * epsilon, axis=0) * B[:, idx]).reshape(-1, 1)
    hidden_states = []
    hidden_states.append(np.argmax(epsilon))
    n = len(psi)
    for i in range(n):
        hidden_states.append(psi[n - i - 1][hidden_states[i - 1]])
    return [index_to_hidden_state(idx) for idx in hidden_states]

## Тестирование

In [15]:
open_states = 'ОРОРОРООРРРРРРРРРРОООООООО'

In [16]:
P = np.array([0.5, 0.5])
P

array([0.5, 0.5])

## Тест 1

In [17]:
B = np.array(
    [
        [0.5, 0.5],
        [0.1, 0.9]
    ],
)
B

array([[0.5, 0.5],
       [0.1, 0.9]])

In [18]:
A = np.array(
    [
        [0.8, 0.2],
        [0.2, 0.8]
    ],
)
A

array([[0.8, 0.2],
       [0.2, 0.8]])

In [19]:
viterbi(open_states, P, A, B)

[1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1]

## Тест 2

In [20]:
B = np.array(
    [
        [0.5,  0.5],
        [0.51, 0.49]
    ],
)
B

array([[0.5 , 0.5 ],
       [0.51, 0.49]])

In [21]:
A = np.array(
    [
        [0.5, 0.5],
        [0.5, 0.5]
    ],
)
A

array([[0.5, 0.5],
       [0.5, 0.5]])

In [22]:
viterbi(open_states, P, A, B)

[2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2]